# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab640dc5979acfb48bfd116a1d5f5681d057db5d86363956e4f0c696098568db9c5dc741e8e7f39adc34f6869badc8e3690ecc789bf8f7e9b5db1560ea134dfa

test:
  secret_key_base: 07cfd82ee62d432f8671fac7e820d2928ecda9e0452af9ffd0f82686aaa3d8c96c34b61a8db49c9435f96d7e5c95556150d4a5741c33e94c0166180250887cf1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
