<% require 'gci-simple-encryption' #%>

development:
  version: "1.1"
  endpoint: "https://soap.prodtest.sj.vindicia.com"
  namespace: "http://soap.vindicia.com"
  password: z8wCZNE6bj85Qcg7mhnUDHMIWZrkph5N
  login: gannett-select_soap
  open_timeout: 600
  read_timeout: 600

production:
  version: "1.1"
  endpoint: "https://soap.vindicia.com"
  namespace: "http://soap.vindicia.com"
  password: z8wCZNE6bj85Qcg7mhnUDHMIWZrkph5N
  login: gannett-select_soap
  open_timeout: 600
  read_timeout: 600
